### ISSUE TITLE
Missing feature from original mod's Project Table

### ISSUE THREAD

**Issue by johnpgr** [Luligabi1/ProjectTableMod#7]
The original mod's Project table had a nice feature that holded a recipe in place after crafting, if you had the resources in the project table's inventory.

It was the whole point of the project table's inventory

 The Project Table from version 1.1:
 

https://github.com/Luligabi1/EnhancedWorkbenches/assets/62309738/9f91c1ad-555d-437c-bb32-5da691a5cffb

How it currently is:

https://github.com/Luligabi1/EnhancedWorkbenches/assets/62309738/c963174a-d5a8-4c71-86db-264e04925f43

**Comment by Luligabi1** [comment]
We're going on a GregTech-ier direction, as it feels far more complete - check #4 for information,
